targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
global_options:
  freezed:freezed:
    runs_before:
      - hive_generator:hive_generator
  hive_generator:hive_generator:
    runs_before:
      - json_serializable:json_serializable
